namespace: 
  name: demo

image: 
  pullPolicy: IfNotPresent
  repository: nginx
  tag: "alpine"

replicaCount: 3

resources: 
  limits: 
    cpu: 50m
    memory: 256Mi
  requests: 
    cpu: 50m
    memory: 256Mi

service: 
  port: 8111
  type: ClusterIP

configmap:
  data: "version: alpine"
