namespace:
 name: staging

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.18.0"

resources: {} 
   limits:
     cpu: 50m
     memory: 128Mi
   requests:
     cpu: 50m
     memory: 128Mi

service:
  type: ClusterIP
  port: 8111

release: "1.18.0"

