--- 
image: 
  pullPolicy: IfNotPresent
  repository: nginx
  tag: "1.17.0"

namespace: 
  name: production

replicaCount: 2

resources: 
  limits: 
    cpu: 70m
    memory: 256Mi
  requests: 
    cpu: 70m
    memory: 256Mi

service: 
  port: 80
  type: NodePort

configmap:
  data: "version: 1.17.0"
