--- 
image: 
  pullPolicy: IfNotPresent
  repository: nginx
  tag: "1.18.0"
namespace: 
  name: staging
release: "1.18.0"
replicaCount: 1
resources: 
  limits: 
    cpu: 50m
    memory: 128Mi
  requests: 
    cpu: 50m
    memory: 128Mi
service: 
  port: 8111
  type: ClusterIP
