image: 
  pullPolicy: IfNotPresent
  repository: nginx
  tag: "alpine"
namespace: 
  name: demo
release: "alpine"
replicaCount: 3
resources: 
  limits: 
    cpu: 50m
    memory: 256Mi
  requests: 
    cpu: 50m
    memory: 256Mi
service: 
  port: 8111
  type: ClusterIP
