--- 
namespace: 
  name: staging

image: 
  pullPolicy: IfNotPresent
  repository: nginx
  tag: "alpine"

replicaCount: 1

resources: 
  limits: 
    cpu: 50m
    memory: 128Mi
  requests: 
    cpu: 50m
    memory: 128Mi

service: 
  port: 8111
  type: ClusterIP

configmap:
  data: "version: 1.18.0"
