apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-alpine
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    #targetPort: 8111
  selector:
    app: nginx
  type: {{ .Values.service.type }}
